version: "3.2"
services:
 www:
# Note: Build to be altered to image: osomanden/debian-noah:latest when in production (moved to github)
#  build: . #Include Dockerfile in current directory
 image: osomanden/debian-noah
#  build: .
  ports:
  - "80:80"
  - "443:443"
  expose:
  - "80"
  - "443"
  volumes:
  - "var:/var/www/html/var/"
  env_file:
    - .env
  restart: always
  networks:
  - frontend
  - backend
  links:
  - db:db
  depends_on:
  - db
 db:
  image: mysql:latest
  cap_add:
  - SYS_NICE  # CAP_SYS_NICE
  ports:
  - "3306:3306"
  command: --default-authentication-plugin=mysql_native_password
  volumes:
  - "./conf/my.cnf:/etc/mysql/conf.d/my.cnf"
  - "./dump/:/docker-entrypoint-initdb.d"
  - "db_data:/var/lib/mysql"
  env_file:
    - .env
  restart: always
  networks:
  - backend
networks:
  frontend:
  backend:
volumes:
  db_data: {}
  var: {}
