version: "3.2"
services:
 www:
  build: . #Include Dockerfile in current directory
  ports:
  - "30001:80"
  - "30443:443"
  expose:
  - "80"
  volumes:
  - ./www:/var/www/html/
  restart: always
  links:
  - db
  networks:
  - frontend
  - backend
  depends_on:
  - db
 db:
  image: mysql:latest
  ports:
  - "3306:3306"
  command: --default-authentication-plugin=mysql_native_password
  volumes:
  - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
  - db_data:/var/lib/mysql
  restart: always
  networks:
  - backend

networks:
  frontend:
  backend:
volumes:
  db_data: {}
